# Generated by Django 4.2.8 on 2024-01-02 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Category Boxes',
                'db_table': 'category_box',
            },
        ),
        migrations.CreateModel(
            name='GradeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.categorybox')),
            ],
            options={
                'verbose_name_plural': 'Grade Boxes',
                'db_table': 'grade_box',
            },
        ),
        migrations.CreateModel(
            name='UnitBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000, null=True)),
                ('is_classic', models.BooleanField(default=False)),
                ('classic_type', models.CharField(max_length=30, null=True)),
                ('order', models.IntegerField(null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.gradebox')),
            ],
            options={
                'verbose_name_plural': 'Unit Boxes',
                'db_table': 'unit_box',
            },
        ),
        migrations.CreateModel(
            name='VideoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('media', models.FileField(default='', max_length=200, upload_to='')),
                ('caption', models.FileField(default='', max_length=200, upload_to='')),
                ('hls_url', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.categorybox')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.gradebox')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.unitbox')),
            ],
            options={
                'verbose_name_plural': 'Video Boxes',
                'db_table': 'video_box',
            },
        ),
        migrations.CreateModel(
            name='WordBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(null=True)),
                ('word_text', models.CharField(max_length=100, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.videobox')),
            ],
            options={
                'verbose_name_plural': 'Word Boxes',
                'db_table': 'word_box',
            },
        ),
        migrations.CreateModel(
            name='StampBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_stamps', models.TextField(blank=True, null=True)),
                ('good_stamps', models.TextField(blank=True, null=True)),
                ('normal_stamps', models.TextField(blank=True, null=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.videobox')),
            ],
            options={
                'verbose_name_plural': 'Stamp Boxes',
                'db_table': 'stamp_box',
            },
        ),
    ]
