# Generated by Django 4.2.8 on 2024-01-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_stampbox_created_at_wordbox_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradebox',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stampbox',
            name='video',
        ),
        migrations.RemoveField(
            model_name='unitbox',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='videobox',
            name='category',
        ),
        migrations.RemoveField(
            model_name='videobox',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='videobox',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='wordbox',
            name='video',
        ),
        migrations.DeleteModel(
            name='CategoryBox',
        ),
        migrations.DeleteModel(
            name='GradeBox',
        ),
        migrations.DeleteModel(
            name='StampBox',
        ),
        migrations.DeleteModel(
            name='UnitBox',
        ),
        migrations.DeleteModel(
            name='VideoBox',
        ),
        migrations.DeleteModel(
            name='WordBox',
        ),
    ]
